# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbd1b30fc14fef2bcb9a75ac25c9d94dd0a5541110e679138e4a0a0dd9cdf3efd8aa86ae13af4757cd8da7feb81c823e09afee473084d9d5794ed6ac5d031509
  slack:
    incoming_webhook_url: <%= ENV["SLACK_INCOMING_WEBHOOK_URL"] %>
    username: "Basecamp"
    icon_emoji: "basecamp" # required slack custom emoji setting about :basecamp:
  basecamp:  # This is optional feature. if you want to use these, require configure
    integration: <%= ENV["BASECAMP_INTEGRATION"] %> # true or false
    client_id: <%= ENV["BASECAMP_CLIENT_ID"] %> # Require register your app to https://launchpad.37signals.com/integrations
    client_secret: <%= ENV["BASECAMP_CLIENT_SECRET"] %>
    account_id: <%= ENV["BASECAMP_ACCOUNT_ID"] %> # https://3.basecamp.com/$ACCOUNT_ID/projects
    redirect_uri: <%= ENV["BASECAMP_AUTH_REDIRECT_URI"] %>

test:
  secret_key_base: 2e297e2fd52de24ec5352eb7d6ac1b7f5e6783d61ba333ecce1dc84bd2e4425701ef6258f8c7b693288217c076d1c7490dfbf9b9ef91da6ab7fa8eb4f0c362d4
  slack:
    incoming_webhook_url: 'https://example.sideci.com'
    username: "Basecamp"
    icon_emoji: "basecamp" # required slack custom emoji setting about :basecamp:
  basecamp:
    integration: <%= ENV["BASECAMP_INTEGRATION"] %>
    client_id: <%= ENV["BASECAMP_CLIENT_ID"] %>
    client_secret: <%= ENV["BASECAMP_CLIENT_SECRET"] %>
    account_id: <%= ENV["BASECAMP_ACCOUNT_ID"] %>
    redirect_uri: <%= ENV["BASECAMP_AUTH_REDIRECT_URI"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  slack:
    incoming_webhook_url: <%= ENV["SLACK_INCOMING_WEBHOOK_URL"] %>
    username: <%= ENV["SLACK_USERNAME"] %>
    icon_emoji: <%= ENV["SLACK_ICON_EMOJI"] %>
  basecamp:
    integration: <%= ENV["BASECAMP_INTEGRATION"] %>
    client_id: <%= ENV["BASECAMP_CLIENT_ID"] %>
    client_secret: <%= ENV["BASECAMP_CLIENT_SECRET"] %>
    account_id: <%= ENV["BASECAMP_ACCOUNT_ID"] %>
    redirect_uri: <%= ENV["BASECAMP_AUTH_REDIRECT_URI"] %>
